"""empty message

Revision ID: 024d28d02ab1
Revises: 215b30712e1a
Create Date: 2022-09-22 15:28:01.944413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024d28d02ab1'
down_revision = '215b30712e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
